import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Nav from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-4 md:px-6 lg:px-12 xl:px-24 flex flex-col min-h-screen`}
      >
       <Nav />
        <main className="flex-1">
        {children}
        </main>
        <footer className="py-4 text-center">
          this website was built by <a href="https://www.linkedin.com/in/kwaghuter-raphael/" target="blank" className="text-blue-500 uppercase font-semibold">Kwaghuter Raphael</a>
        </footer>
      </body>
    </html>
  );
}
